package pe.edu.upc.dew.ventapasajesbus.dao;
// Generated 04/12/2010 07:30:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Asiento generated by hbm2java
 */
public class Asiento  implements java.io.Serializable {


     private Integer nuAsiento;
     private Set reservas = new HashSet(0);

    public Asiento() {
    }

    public Asiento(Set reservas) {
       this.reservas = reservas;
    }
   
    public Integer getNuAsiento() {
        return this.nuAsiento;
    }
    
    public void setNuAsiento(Integer nuAsiento) {
        this.nuAsiento = nuAsiento;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


