package pe.edu.upc.dew.ventapasajesbus.dao;
// Generated 04/12/2010 10:53:59 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresatransporte generated by hbm2java
 */
public class Empresatransporte  implements java.io.Serializable {


     private Integer coEmpresaTransporte;
     private String noEmpresaTransporte;
     private Set buses = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Set rutas = new HashSet(0);
     private Set clientes = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Empresatransporte() {
    }

	
    public Empresatransporte(String noEmpresaTransporte) {
        this.noEmpresaTransporte = noEmpresaTransporte;
    }
    public Empresatransporte(String noEmpresaTransporte, Set buses, Set reservas, Set rutas, Set clientes, Set usuarios) {
       this.noEmpresaTransporte = noEmpresaTransporte;
       this.buses = buses;
       this.reservas = reservas;
       this.rutas = rutas;
       this.clientes = clientes;
       this.usuarios = usuarios;
    }
   
    public Integer getCoEmpresaTransporte() {
        return this.coEmpresaTransporte;
    }
    
    public void setCoEmpresaTransporte(Integer coEmpresaTransporte) {
        this.coEmpresaTransporte = coEmpresaTransporte;
    }
    public String getNoEmpresaTransporte() {
        return this.noEmpresaTransporte;
    }
    
    public void setNoEmpresaTransporte(String noEmpresaTransporte) {
        this.noEmpresaTransporte = noEmpresaTransporte;
    }
    public Set getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set buses) {
        this.buses = buses;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Set rutas) {
        this.rutas = rutas;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


