package pe.edu.upc.dew.ventapasajesbus.dao;
// Generated 05/12/2010 12:44:53 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private String coPlaca;
     private Empresatransporte empresatransporte;
     private int qtCapacidad;
     private Set rutas = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String coPlaca, Empresatransporte empresatransporte, int qtCapacidad) {
        this.coPlaca = coPlaca;
        this.empresatransporte = empresatransporte;
        this.qtCapacidad = qtCapacidad;
    }
    public Bus(String coPlaca, Empresatransporte empresatransporte, int qtCapacidad, Set rutas) {
       this.coPlaca = coPlaca;
       this.empresatransporte = empresatransporte;
       this.qtCapacidad = qtCapacidad;
       this.rutas = rutas;
    }
   
    public String getCoPlaca() {
        return this.coPlaca;
    }
    
    public void setCoPlaca(String coPlaca) {
        this.coPlaca = coPlaca;
    }
    public Empresatransporte getEmpresatransporte() {
        return this.empresatransporte;
    }
    
    public void setEmpresatransporte(Empresatransporte empresatransporte) {
        this.empresatransporte = empresatransporte;
    }
    public int getQtCapacidad() {
        return this.qtCapacidad;
    }
    
    public void setQtCapacidad(int qtCapacidad) {
        this.qtCapacidad = qtCapacidad;
    }
    public Set getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Set rutas) {
        this.rutas = rutas;
    }




}


