package pe.edu.upc.dew.ventapasajesbus.dao;
// Generated 04/12/2010 10:53:59 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer coCiudad;
     private String noCiudad;
     private Set rutasForNoCiudadDestino = new HashSet(0);
     private Set rutasForNoCiudadOrigen = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(String noCiudad) {
        this.noCiudad = noCiudad;
    }
    public Ciudad(String noCiudad, Set rutasForNoCiudadDestino, Set rutasForNoCiudadOrigen) {
       this.noCiudad = noCiudad;
       this.rutasForNoCiudadDestino = rutasForNoCiudadDestino;
       this.rutasForNoCiudadOrigen = rutasForNoCiudadOrigen;
    }
   
    public Integer getCoCiudad() {
        return this.coCiudad;
    }
    
    public void setCoCiudad(Integer coCiudad) {
        this.coCiudad = coCiudad;
    }
    public String getNoCiudad() {
        return this.noCiudad;
    }
    
    public void setNoCiudad(String noCiudad) {
        this.noCiudad = noCiudad;
    }
    public Set getRutasForNoCiudadDestino() {
        return this.rutasForNoCiudadDestino;
    }
    
    public void setRutasForNoCiudadDestino(Set rutasForNoCiudadDestino) {
        this.rutasForNoCiudadDestino = rutasForNoCiudadDestino;
    }
    public Set getRutasForNoCiudadOrigen() {
        return this.rutasForNoCiudadOrigen;
    }
    
    public void setRutasForNoCiudadOrigen(Set rutasForNoCiudadOrigen) {
        this.rutasForNoCiudadOrigen = rutasForNoCiudadOrigen;
    }




}


