package pe.edu.upc.dew.ventapasajesbus.dao;
// Generated 05/12/2010 12:44:53 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String coDni;
     private Empresatransporte empresatransporte;
     private String noCliente;
     private String noDireccion;
     private String nuTelefono;
     private String noEmail;
     private Set reservas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String coDni, Empresatransporte empresatransporte, String noCliente, String noDireccion, String nuTelefono, String noEmail) {
        this.coDni = coDni;
        this.empresatransporte = empresatransporte;
        this.noCliente = noCliente;
        this.noDireccion = noDireccion;
        this.nuTelefono = nuTelefono;
        this.noEmail = noEmail;
    }
    public Cliente(String coDni, Empresatransporte empresatransporte, String noCliente, String noDireccion, String nuTelefono, String noEmail, Set reservas) {
       this.coDni = coDni;
       this.empresatransporte = empresatransporte;
       this.noCliente = noCliente;
       this.noDireccion = noDireccion;
       this.nuTelefono = nuTelefono;
       this.noEmail = noEmail;
       this.reservas = reservas;
    }
   
    public String getCoDni() {
        return this.coDni;
    }
    
    public void setCoDni(String coDni) {
        this.coDni = coDni;
    }
    public Empresatransporte getEmpresatransporte() {
        return this.empresatransporte;
    }
    
    public void setEmpresatransporte(Empresatransporte empresatransporte) {
        this.empresatransporte = empresatransporte;
    }
    public String getNoCliente() {
        return this.noCliente;
    }
    
    public void setNoCliente(String noCliente) {
        this.noCliente = noCliente;
    }
    public String getNoDireccion() {
        return this.noDireccion;
    }
    
    public void setNoDireccion(String noDireccion) {
        this.noDireccion = noDireccion;
    }
    public String getNuTelefono() {
        return this.nuTelefono;
    }
    
    public void setNuTelefono(String nuTelefono) {
        this.nuTelefono = nuTelefono;
    }
    public String getNoEmail() {
        return this.noEmail;
    }
    
    public void setNoEmail(String noEmail) {
        this.noEmail = noEmail;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


