package pe.edu.upc.dew.ventapasajesbus.dao;
// Generated 04/12/2010 07:30:12 PM by Hibernate Tools 3.2.1.GA



/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer coTicket;
     private Ruta ruta;
     private Asiento asiento;
     private Empresatransporte empresatransporte;
     private Cliente cliente;
     private boolean flPagado;

    public Reserva() {
    }

    public Reserva(Ruta ruta, Asiento asiento, Empresatransporte empresatransporte, Cliente cliente, boolean flPagado) {
       this.ruta = ruta;
       this.asiento = asiento;
       this.empresatransporte = empresatransporte;
       this.cliente = cliente;
       this.flPagado = flPagado;
    }
   
    public Integer getCoTicket() {
        return this.coTicket;
    }
    
    public void setCoTicket(Integer coTicket) {
        this.coTicket = coTicket;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Asiento getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(Asiento asiento) {
        this.asiento = asiento;
    }
    public Empresatransporte getEmpresatransporte() {
        return this.empresatransporte;
    }
    
    public void setEmpresatransporte(Empresatransporte empresatransporte) {
        this.empresatransporte = empresatransporte;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public boolean isFlPagado() {
        return this.flPagado;
    }
    
    public void setFlPagado(boolean flPagado) {
        this.flPagado = flPagado;
    }




}


