package pe.edu.upc.dew.ventapasajesbus.dao;
// Generated 04/12/2010 07:30:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer coRuta;
     private Ciudad ciudadByNoCiudadDestino;
     private Bus bus;
     private Ciudad ciudadByNoCiudadOrigen;
     private Empresatransporte empresatransporte;
     private Date feHoraSalida;
     private Date feHoraLlegada;
     private double ssTarifa;
     private Set reservas = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(Ciudad ciudadByNoCiudadDestino, Bus bus, Ciudad ciudadByNoCiudadOrigen, Empresatransporte empresatransporte, Date feHoraSalida, Date feHoraLlegada, double ssTarifa) {
        this.ciudadByNoCiudadDestino = ciudadByNoCiudadDestino;
        this.bus = bus;
        this.ciudadByNoCiudadOrigen = ciudadByNoCiudadOrigen;
        this.empresatransporte = empresatransporte;
        this.feHoraSalida = feHoraSalida;
        this.feHoraLlegada = feHoraLlegada;
        this.ssTarifa = ssTarifa;
    }
    public Ruta(Ciudad ciudadByNoCiudadDestino, Bus bus, Ciudad ciudadByNoCiudadOrigen, Empresatransporte empresatransporte, Date feHoraSalida, Date feHoraLlegada, double ssTarifa, Set reservas) {
       this.ciudadByNoCiudadDestino = ciudadByNoCiudadDestino;
       this.bus = bus;
       this.ciudadByNoCiudadOrigen = ciudadByNoCiudadOrigen;
       this.empresatransporte = empresatransporte;
       this.feHoraSalida = feHoraSalida;
       this.feHoraLlegada = feHoraLlegada;
       this.ssTarifa = ssTarifa;
       this.reservas = reservas;
    }
   
    public Integer getCoRuta() {
        return this.coRuta;
    }
    
    public void setCoRuta(Integer coRuta) {
        this.coRuta = coRuta;
    }
    public Ciudad getCiudadByNoCiudadDestino() {
        return this.ciudadByNoCiudadDestino;
    }
    
    public void setCiudadByNoCiudadDestino(Ciudad ciudadByNoCiudadDestino) {
        this.ciudadByNoCiudadDestino = ciudadByNoCiudadDestino;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public Ciudad getCiudadByNoCiudadOrigen() {
        return this.ciudadByNoCiudadOrigen;
    }
    
    public void setCiudadByNoCiudadOrigen(Ciudad ciudadByNoCiudadOrigen) {
        this.ciudadByNoCiudadOrigen = ciudadByNoCiudadOrigen;
    }
    public Empresatransporte getEmpresatransporte() {
        return this.empresatransporte;
    }
    
    public void setEmpresatransporte(Empresatransporte empresatransporte) {
        this.empresatransporte = empresatransporte;
    }
    public Date getFeHoraSalida() {
        return this.feHoraSalida;
    }
    
    public void setFeHoraSalida(Date feHoraSalida) {
        this.feHoraSalida = feHoraSalida;
    }
    public Date getFeHoraLlegada() {
        return this.feHoraLlegada;
    }
    
    public void setFeHoraLlegada(Date feHoraLlegada) {
        this.feHoraLlegada = feHoraLlegada;
    }
    public double getSsTarifa() {
        return this.ssTarifa;
    }
    
    public void setSsTarifa(double ssTarifa) {
        this.ssTarifa = ssTarifa;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


